//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBookTestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONEBOOK
    {
        public long Id { get; set; }
        public string NAME { get; set; }
        public string PHONENUMBER { get; set; }
        public string ADDRESS { get; set; }
    }
}
